import os
import json
import uuid
from core.utils import parse_video_id
import logging
from typing import Optional

from sqlalchemy import select

from core.config import settings
from core.database import AsyncSessionLocal
from models.transcript import Transcript
from models.vision import VideoFrame, OCRResult, FrameScore

logger = logging.getLogger(__name__)

class MergeServiceError(Exception):
    pass

class MergeService:
    async def generate_merged_markdown(
        self,
        video_id: str,
        topics_data: dict,
        assessments_data: dict,
        examples_data: dict = None,
        support_data: dict = None,
        glossary_data: dict = None,
        qa_data: dict = None,
        mind_map_data: dict = None,
        # Phase 2 enrichment
        concepts_data: dict = None,
        objectives_data: dict = None,
        prerequisites_data: dict = None,
        difficulty_data: dict = None,
        # Phase 3-4 enrichment
        definitions_data: dict = None,
        step_by_step_data: dict = None,
        applications_data: dict = None,
        misconceptions_data: dict = None,
        # Phase 5 enrichment
        learning_path_data: dict = None,
        # Modular Generators
        formula_data: dict = None,
        interview_data: dict = None,
        revision_data: dict = None,
    ) -> Optional[str]:
        """
        Generates a heavily formatted Markdown document from AI outputs.

        Renders all pipeline phases:
          Phase 1–2 : Summary, Topics, Notes, Concepts, Learning Objectives,
                      Prerequisites, Difficulty
          Phase 3–4 : Definitions, Step-by-Step, Applications, Examples,
                      Misconceptions & Edge Cases, Learning Support
          Phase 5   : Assessments (Quiz + Flashcards), Learning Path
          Phase 7   : QA Warnings, Mind Map
          Glossary  : Terms and definitions
        """
        logger.info("Compiling AI Markdown for video %s", video_id)
        
        output_dir = os.path.join(settings.OUTPUT_DIR, video_id)
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, "merged_transcript.md")
        
        md_lines = [
            "# AI Video Notes & Analysis\n",
            "> *These notes were intelligently generated by EduScribe AI.*\n",
            "---\n"
        ]

        # ── QA Warnings (shown first as a banner) ─────────────────────────────
        if qa_data:
            warnings = qa_data.get("qa_warnings", [])
            if warnings:
                md_lines.append("> [!WARNING]")
                md_lines.append("> **Quality Assurance Alert**: The AI detected potential factual inconsistencies in these notes compared to the original video.\n>")
                for w in warnings:
                    issue = w.get('issue', '')
                    correction = w.get('correction', '')
                    md_lines.append(f"> - **Issue:** {issue} (Correction: {correction})")
                md_lines.append("\n---\n")

        # ── Executive Summary ──────────────────────────────────────────────────
        summary = topics_data.get("summary", "")
        if summary:
            md_lines.append("## 📋 Executive Summary\n")
            md_lines.append(f"{summary}\n")
            md_lines.append("---\n")

        # ── Difficulty & Metadata ──────────────────────────────────────────────
        if difficulty_data:
            label = difficulty_data.get("difficulty_label", "")
            level = difficulty_data.get("overall_difficulty", "")
            justification = difficulty_data.get("difficulty_justification", "")
            suitable_for = difficulty_data.get("suitable_for", [])
            if label:
                md_lines.append("## 🎯 Difficulty & Audience\n")
                md_lines.append(f"**Difficulty Level:** {label} ({level}/5)")
                if justification:
                    md_lines.append(f"\n{justification}\n")
                if suitable_for:
                    md_lines.append(f"\n**Best suited for:** {', '.join(suitable_for)}\n")
                md_lines.append("\n---\n")

        # ── Learning Objectives ────────────────────────────────────────────────
        if objectives_data:
            objectives = objectives_data.get("learning_objectives", [])
            if objectives:
                md_lines.append("## 🎓 Learning Objectives\n")
                md_lines.append("After completing this lecture, you will be able to:\n")
                for obj in objectives:
                    objective = obj.get("objective", "")
                    bloom = obj.get("bloom_level", "")
                    if objective:
                        bloom_badge = f" `{bloom}`" if bloom else ""
                        md_lines.append(f"- {objective}{bloom_badge}")
                target = objectives_data.get("target_audience", "")
                est_time = objectives_data.get("estimated_study_time_minutes", 0)
                if target:
                    md_lines.append(f"\n**Target Audience:** {target}")
                if est_time:
                    md_lines.append(f"\n**Estimated Study Time:** {est_time} minutes")
                md_lines.append("\n\n---\n")

        # ── Prerequisites & Dependencies ───────────────────────────────────────
        if prerequisites_data:
            prereqs = prerequisites_data.get("prerequisites", [])
            deps = prerequisites_data.get("concept_dependencies", [])
            suggested = prerequisites_data.get("suggested_prior_courses", [])
            if prereqs or deps or suggested:
                md_lines.append("## 📚 Prerequisites & Dependencies\n")
                if prereqs:
                    md_lines.append("### Required Knowledge\n")
                    for p in prereqs:
                        topic = p.get("topic", "")
                        importance = p.get("importance", "")
                        reason = p.get("reason", "")
                        if topic:
                            md_lines.append(f"- **{topic}** `{importance}` — {reason}")
                    md_lines.append("")
                if deps:
                    md_lines.append("### Concept Dependencies\n")
                    for d in deps:
                        concept = d.get("concept", "")
                        depends_on = d.get("depends_on", "")
                        if concept and depends_on:
                            md_lines.append(f"- **{concept}** depends on → *{depends_on}*")
                    md_lines.append("")
                if suggested:
                    md_lines.append(f"\n**Suggested Prior Courses/Topics:** {', '.join(suggested)}\n")
                md_lines.append("\n---\n")

        # ── Mind Map ────────────────────────────────────────────────────────────
        if mind_map_data:
            mermaid_code = mind_map_data.get("content", "")
            if mermaid_code:
                md_lines.append("## 🧠 Concept Mind Map\n")
                md_lines.append("```mermaid")
                md_lines.append(mermaid_code)
                md_lines.append("```\n")
                md_lines.append("---\n")

        # ── Detailed Topics & Notes ────────────────────────────────────────────
        topics = topics_data.get("topics", [])
        if topics:
            md_lines.append("## 📝 Detailed Topics\n")
            for t in topics:
                title = t.get("title", "Topic")
                start = t.get("start_time", "")
                
                md_lines.append(f"### {title} ⏱️ {start}\n")
                
                notes = t.get("notes_markdown", "")
                if notes:
                    md_lines.append(f"{notes}\n")
                    
                takeaways = t.get("key_takeaways", [])
                if takeaways:
                    md_lines.append("\n**Key Takeaways:**")
                    for tk in takeaways:
                        md_lines.append(f"- {tk}")
                        
                citations = t.get("citations", [])
                if citations:
                    md_lines.append("\n**Sources:**")
                    for cit in citations:
                        ts = cit.get("timestamp", "")
                        src = cit.get("source", "transcript")
                        md_lines.append(f"- *[{ts}] ({src})*")
                        
                md_lines.append("\n---\n")

        # ── Key Concepts & Keywords ────────────────────────────────────────────
        if concepts_data:
            concepts = concepts_data.get("concepts", [])
            keywords = concepts_data.get("keywords", [])
            if concepts:
                md_lines.append("## 🔑 Key Concepts\n")
                for c in concepts:
                    importance_icon = "🔴" if c.importance == "high" else ("🟡" if c.importance == "medium" else "🟢")
                    md_lines.append(f"- {importance_icon} **{c.name}** `{c.category}` — {c.brief_description}")
                if keywords:
                    md_lines.append(f"\n**Keywords:** {', '.join([f'`{k}`' for k in keywords])}\n")
                md_lines.append("\n---\n")

        # ── Definitions ────────────────────────────────────────────────────────
        if definitions_data:
            definitions = definitions_data.get("definitions", [])
            if definitions:
                md_lines.append("## 📖 Key Definitions\n")
                for d in definitions:
                    term = d.get("term", "")
                    definition = d.get("definition", "")
                    synonyms = d.get("synonyms", [])
                    related = d.get("related_terms", [])
                    if term and definition:
                        md_lines.append(f"**{term}**")
                        md_lines.append(f": {definition}")
                        if synonyms:
                            md_lines.append(f"  *Also known as: {', '.join(synonyms)}*")
                        if related:
                            md_lines.append(f"  *Related: {', '.join(related)}*")
                        md_lines.append("")
                md_lines.append("---\n")

        # ── Step-by-Step Explanations ──────────────────────────────────────────
        if step_by_step_data:
            explanations = step_by_step_data.get("step_by_step_explanations", [])
            if explanations:
                md_lines.append("## 🔢 Step-by-Step Explanations\n")
                for expl in explanations:
                    process_name = expl.get("process_name", "")
                    overview = expl.get("overview", "")
                    steps = expl.get("steps", [])
                    time_complexity = expl.get("time_complexity", "")
                    space_complexity = expl.get("space_complexity", "")
                    if process_name:
                        md_lines.append(f"### {process_name}\n")
                        if overview:
                            md_lines.append(f"{overview}\n")
                        if time_complexity or space_complexity:
                            complexity_parts = []
                            if time_complexity:
                                complexity_parts.append(f"Time: `{time_complexity}`")
                            if space_complexity:
                                complexity_parts.append(f"Space: `{space_complexity}`")
                            md_lines.append(f"**Complexity:** {' | '.join(complexity_parts)}\n")
                        for step in steps:
                            step_num = step.get("step_number", "")
                            action = step.get("action", "")
                            explanation = step.get("explanation", "")
                            example = step.get("example", "")
                            md_lines.append(f"**Step {step_num}:** {action}")
                            if explanation:
                                md_lines.append(f"  → {explanation}")
                            if example:
                                md_lines.append(f"  *Example: {example}*")
                        pitfalls = expl.get("common_pitfalls", [])
                        if pitfalls:
                            md_lines.append(f"\n⚠️ **Common Pitfalls:** {', '.join(pitfalls)}")
                        md_lines.append("")
                md_lines.append("---\n")

        # ── Examples & Analogies ───────────────────────────────────────────────
        if examples_data:
            examples = examples_data.get("examples", [])
            if examples:
                md_lines.append("## 💡 Educational Examples & Analogies\n")
                for ex in examples:
                    concept = ex.get("concept", "Concept")
                    md_lines.append(f"### {concept}\n")
                    
                    analogy = ex.get("real_world_analogy", "")
                    if analogy:
                        md_lines.append(f"**🌍 Real-World Analogy:**\n{analogy}\n")
                        
                    numerical = ex.get("numerical_example", "")
                    if numerical and str(numerical).lower() != "null":
                        md_lines.append(f"**🧮 Numerical Example:**\n{numerical}\n")
                        
                    programming = ex.get("programming_example", "")
                    if programming and str(programming).lower() != "null":
                        md_lines.append(f"**💻 Programming Example:**\n```\n{programming}\n```\n")
                md_lines.append("\n---\n")

        # ── Real-World Applications ────────────────────────────────────────────
        if applications_data:
            rw_apps = applications_data.get("real_world_applications", [])
            industry_cases = applications_data.get("industry_use_cases", [])
            career = applications_data.get("career_relevance", [])
            if rw_apps or industry_cases:
                md_lines.append("## 🌐 Real-World Applications\n")
                for app in rw_apps:
                    concept = app.get("concept", "")
                    application = app.get("application", "")
                    industries = app.get("industries", [])
                    specific = app.get("specific_example", "")
                    if concept:
                        md_lines.append(f"### {concept}\n")
                        if application:
                            md_lines.append(f"{application}\n")
                        if specific:
                            md_lines.append(f"*Example:* {specific}\n")
                        if industries:
                            md_lines.append(f"**Industries:** {', '.join(industries)}")
                        md_lines.append("")
                if industry_cases:
                    md_lines.append("### Industry-Specific Use Cases\n")
                    for uc in industry_cases:
                        industry = uc.get("industry", "")
                        use_case = uc.get("use_case", "")
                        tools = uc.get("tools_used", [])
                        if industry:
                            md_lines.append(f"**{industry}:** {use_case}")
                            if tools:
                                md_lines.append(f"  *Tools: {', '.join(tools)}*")
                if career:
                    md_lines.append(f"\n**Career Relevance:** {', '.join(career)}\n")
                md_lines.append("\n---\n")

        # ── Misconceptions & Edge Cases ────────────────────────────────────────
        if misconceptions_data:
            misconceptions = misconceptions_data.get("misconceptions", [])
            edge_cases = misconceptions_data.get("edge_cases", [])
            interview_qs = misconceptions_data.get("interview_questions", [])
            if misconceptions or edge_cases or interview_qs:
                md_lines.append("## ⚠️ Misconceptions, Edge Cases & Interview Prep\n")
                if misconceptions:
                    md_lines.append("### ❌ Common Misconceptions\n")
                    for m in misconceptions:
                        misconception = m.get("misconception", "")
                        correct = m.get("correct_understanding", "")
                        why = m.get("why_it_happens", "")
                        if misconception:
                            md_lines.append(f"**❌ Misconception:** {misconception}")
                            if correct:
                                md_lines.append(f"**✅ Correct:** {correct}")
                            if why:
                                md_lines.append(f"*Why it happens:* {why}")
                            md_lines.append("")
                if edge_cases:
                    md_lines.append("### 🔍 Edge Cases\n")
                    for ec in edge_cases:
                        scenario = ec.get("scenario", "")
                        what = ec.get("what_happens", "")
                        how = ec.get("how_to_handle", "")
                        if scenario:
                            md_lines.append(f"**Scenario:** {scenario}")
                            if what:
                                md_lines.append(f"**Behavior:** {what}")
                            if how:
                                md_lines.append(f"**Handling:** {how}")
                            md_lines.append("")
                if interview_qs:
                    md_lines.append("### 💼 Interview Questions\n")
                    for iq in interview_qs:
                        question = iq.get("question", "")
                        difficulty = iq.get("difficulty", "")
                        key_points = iq.get("key_points_to_cover", [])
                        if question:
                            diff_badge = f" `{difficulty}`" if difficulty else ""
                            md_lines.append(f"**Q: {question}**{diff_badge}")
                            if key_points:
                                md_lines.append("Key points to cover:")
                                for kp in key_points:
                                    md_lines.append(f"  - {kp}")
                            md_lines.append("")
                md_lines.append("---\n")

        # ── Learning Support (Mistakes, Best Practices) ────────────────────────
        if support_data:
            md_lines.append("## 🎓 Advanced Learning Support\n")
            
            mistakes = support_data.get("common_mistakes", [])
            if mistakes:
                md_lines.append("### ⚠️ Common Mistakes")
                for m in mistakes:
                    md_lines.append(f"- {m}")
                md_lines.append("")
                
            misconceptions_legacy = support_data.get("misconceptions", [])
            if misconceptions_legacy:
                md_lines.append("### ❌ Potential Misconceptions")
                for m in misconceptions_legacy:
                    md_lines.append(f"- {m}")
                md_lines.append("")
                
            best_practices = support_data.get("best_practices", [])
            if best_practices:
                md_lines.append("### ✅ Best Practices")
                for bp in best_practices:
                    md_lines.append(f"- {bp}")
                md_lines.append("")
                
            edge_cases_legacy = support_data.get("edge_cases", [])
            if edge_cases_legacy:
                md_lines.append("### 🔍 Edge Cases")
                for ec in edge_cases_legacy:
                    md_lines.append(f"- {ec}")
                md_lines.append("")
            
            md_lines.append("---\n")

        # ── Glossary ───────────────────────────────────────────────────────────
        if glossary_data:
            glossary = glossary_data.get("glossary", [])
            if glossary:
                md_lines.append("## 📖 Glossary of Terms\n")
                md_lines.append("| Term | Definition |")
                md_lines.append("|------|------------|")
                for item in glossary:
                    term = item.get("term", "")
                    definition = item.get("definition", "")
                    # Escape pipe characters for markdown tables
                    term = term.replace("|", "\\|")
                    definition = definition.replace("|", "\\|").replace("\n", " ")
                    md_lines.append(f"| **{term}** | {definition} |")
                md_lines.append("\n---\n")

        # ── Quiz ───────────────────────────────────────────────────────────────
        quiz = assessments_data.get("quiz", [])
        if quiz:
            md_lines.append("## 📝 Knowledge Check Quiz\n")
            for i, q in enumerate(quiz, 1):
                md_lines.append(f"**Q{i}: {q.get('question', '')}**")
                for opt in q.get('options', []):
                    md_lines.append(f"- {opt}")
                md_lines.append(f"\n<details><summary><b>Reveal Answer</b></summary>")
                md_lines.append(f"<b>Correct Answer:</b> {q.get('correct_answer', '')}<br>")
                md_lines.append(f"<i>Explanation:</i> {q.get('explanation', '')}")
                md_lines.append(f"</details>\n")
            md_lines.append("---\n")

        # ── Flashcards ──────────────────────────────────────────────────────────
        flashcards = assessments_data.get("flashcards", [])
        if flashcards:
            md_lines.append("## 📇 Study Flashcards\n")
            for i, card in enumerate(flashcards, 1):
                md_lines.append(f"**Card {i}: {card.get('front', '')}**")
                md_lines.append(f"> {card.get('back', '')}\n")

        # ── Formula Sheet ───────────────────────────────────────────────────────
        if formula_data:
            formulas = formula_data.get("formulas", [])
            if formulas:
                md_lines.append("## 🧮 Formula Sheet\n")
                for f in formulas:
                    name = f.get("name", "")
                    expr = f.get("expression", "")
                    ctx = f.get("context", "")
                    md_lines.append(f"### {name}")
                    if expr:
                        md_lines.append(f"**Formula:**\n```math\n{expr}\n```")
                    if ctx:
                        md_lines.append(f"**Context:** {ctx}")
                    md_lines.append("")
                md_lines.append("---\n")

        # ── Interview Questions ─────────────────────────────────────────────────
        if interview_data:
            tq = interview_data.get("technical_questions", [])
            cq = interview_data.get("conceptual_questions", [])
            if tq or cq:
                md_lines.append("## 🎤 Interview & Viva Questions\n")
                
                if tq:
                    md_lines.append("### Technical Questions\n")
                    for i, q in enumerate(tq, 1):
                        md_lines.append(f"**Q{i}: {q.get('question', '')}**")
                        ans_pts = q.get('expected_answer_points', [])
                        if ans_pts:
                            md_lines.append(f"<details><summary><b>Expected Answer Points</b></summary>")
                            md_lines.append("<ul>")
                            for pt in ans_pts:
                                md_lines.append(f"<li>{pt}</li>")
                            md_lines.append("</ul>")
                            md_lines.append(f"</details>\n")
                
                if cq:
                    md_lines.append("### Conceptual Questions\n")
                    for i, q in enumerate(cq, 1):
                        md_lines.append(f"**Q{i}: {q.get('question', '')}**")
                        ans_pts = q.get('expected_answer_points', [])
                        if ans_pts:
                            md_lines.append(f"<details><summary><b>Expected Answer Points</b></summary>")
                            md_lines.append("<ul>")
                            for pt in ans_pts:
                                md_lines.append(f"<li>{pt}</li>")
                            md_lines.append("</ul>")
                            md_lines.append(f"</details>\n")
                md_lines.append("---\n")

        # ── Revision Sheet ──────────────────────────────────────────────────────
        if revision_data:
            facts = revision_data.get("quick_facts", [])
            must_know = revision_data.get("must_know_points", [])
            if facts or must_know:
                md_lines.append("## ⚡ Quick Revision Sheet\n")
                if facts:
                    md_lines.append("### Quick Facts")
                    for fact in facts:
                        md_lines.append(f"- {fact}")
                    md_lines.append("")
                if must_know:
                    md_lines.append("### Must Know Points")
                    for mk in must_know:
                        md_lines.append(f"- {mk}")
                    md_lines.append("")
                md_lines.append("---\n")

        # ── Learning Path ───────────────────────────────────────────────────────
        if learning_path_data:
            path_steps = learning_path_data.get("learning_path", [])
            milestones = learning_path_data.get("mastery_milestones", [])
            total_hours = learning_path_data.get("total_estimated_hours", 0)
            practice = learning_path_data.get("recommended_practice", [])
            if path_steps:
                md_lines.append("\n---\n")
                md_lines.append("## 🗺️ Recommended Learning Path\n")
                if total_hours:
                    md_lines.append(f"**Total Estimated Time:** {total_hours} hours\n")
                for step in path_steps:
                    step_num = step.get("step", "")
                    topic = step.get("topic", "")
                    reason = step.get("reason", "")
                    resources = step.get("resources", [])
                    hours = step.get("estimated_hours", "")
                    if topic:
                        md_lines.append(f"**Step {step_num}:** {topic} ({hours}h)")
                        if reason:
                            md_lines.append(f"  → {reason}")
                        if resources:
                            md_lines.append(f"  *Resources: {', '.join(resources)}*")
                if milestones:
                    md_lines.append("\n**Mastery Milestones:**")
                    for ms in milestones:
                        milestone = ms.get("milestone", "")
                        verify = ms.get("how_to_verify", "")
                        if milestone:
                            md_lines.append(f"- ✓ {milestone}")
                            if verify:
                                md_lines.append(f"  *Verify by: {verify}*")
                if practice:
                    md_lines.append("\n**Recommended Practice:**")
                    for p in practice:
                        md_lines.append(f"- {p}")

        try:
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write("\n".join(md_lines))
            logger.info("Merged markdown generated successfully at %s", output_path)
            return output_path
        except Exception as e:
            logger.error("Failed to write markdown for video %s: %s", video_id, e)
            return None

    def _format_time(self, seconds: float) -> str:
        """Format seconds into HH:MM:SS or MM:SS."""
        if seconds is None:
            return "00:00"
        m, s = divmod(int(seconds), 60)
        h, m = divmod(m, 60)
        if h > 0:
            return f"{h:02d}:{m:02d}:{s:02d}"
        return f"{m:02d}:{s:02d}"

merge_service = MergeService()
