"""init phase 1

Revision ID: 076cc1a5615e
Revises: 
Create Date: 2026-06-12 12:13:39.137751

"""
from typing import Sequence, Union

# pyrefly: ignore [missing-import]
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '076cc1a5615e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.Enum('UPLOAD', 'YOUTUBE', name='sourcetype'), nullable=False),
    sa.Column('youtube_url', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('video_path', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('UPLOADING', 'PROCESSING', 'TRANSCRIBING', 'COMPLETED', 'FAILED', name='videostatus'), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcripts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('transcript_path', sa.String(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcripts')
    op.drop_table('videos')
    # ### end Alembic commands ###
