"""add_video_telemetry

Revision ID: 1ee999d38e71
Revises: ee76f55834c6
Create Date: 2026-06-13 14:35:38.775053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee999d38e71'
down_revision: Union[str, None] = 'ee76f55834c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('progress_percent', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('current_step', sa.String(length=100), nullable=True))
    op.add_column('videos', sa.Column('processing_time_seconds', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('estimated_time_remaining_seconds', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'estimated_time_remaining_seconds')
    op.drop_column('videos', 'processing_time_seconds')
    op.drop_column('videos', 'current_step')
    op.drop_column('videos', 'progress_percent')
    # ### end Alembic commands ###
