"""Add vision models

Revision ID: 4f17a290ae78
Revises: 1ee999d38e71
Create Date: 2026-07-28 20:46:28.862748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f17a290ae78'
down_revision: Union[str, None] = '1ee999d38e71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_frames',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('frame_path', sa.String(), nullable=False),
    sa.Column('scene_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frame_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('frame_id', sa.UUID(), nullable=False),
    sa.Column('blur_score', sa.Float(), nullable=True),
    sa.Column('phash', sa.String(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['video_frames.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('frame_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('frame_id', sa.UUID(), nullable=False),
    sa.Column('transcript_similarity', sa.Float(), nullable=True),
    sa.Column('visual_importance_score', sa.Float(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['video_frames.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('frame_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=True),
    sa.Column('clean_text', sa.String(), nullable=True),
    sa.Column('average_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['frame_id'], ['video_frames.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocr_results')
    op.drop_table('frame_scores')
    op.drop_table('frame_metadata')
    op.drop_table('video_frames')
    # ### end Alembic commands ###
