"""add_error_message

Revision ID: 66739728efc9
Revises: 94ff41ac2ac1
Create Date: 2026-06-13 13:30:46.062217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66739728efc9'
down_revision: Union[str, None] = '94ff41ac2ac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'error_message')
    # ### end Alembic commands ###
