"""Add thumbnail and channel_name

Revision ID: c47691e40a3e
Revises: 076cc1a5615e
Create Date: 2026-06-12 16:38:39.180169

"""
from typing import Sequence, Union

# pyrefly: ignore [missing-import]
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47691e40a3e'
down_revision: Union[str, None] = '076cc1a5615e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('thumbnail', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('channel_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'channel_name')
    op.drop_column('videos', 'thumbnail')
    # ### end Alembic commands ###
